package:
    name: psen_processing
    version: 1.2.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bottle
        - bsread >=1.2.0
        - requests

build:
  entry_points:
    - psen_processing = psen_processing.start_processing:main

about:
    home: https://github.com/paulscherrerinstitute/psen_processing
