API_PREFIX = ""
DEFAULT_REST_API_INTERFACE = "0.0.0.0"
DEFAULT_REST_API_PORT = 11000

DEFAULT_LOGGING_LEVEL = "INFO"
DEFAULT_OUTPUT_STREAM_PORT = 8888

DEFAULT_ROI_SIGNAL = None
DEFAULT_ROI_BACKGROUND = None

PROCESSOR_START_TIMEOUT = 1

INPUT_STREAM_QUEUE_SIZE = 100
INPUT_STREAM_RECEIVE_TIMEOUT = 1
OUTPUT_STREAM_SEND_TIMEOUT = 1

EPICS_PV_SUFFIX_IMAGE = ":FPICTURE"
